[connections.supabase]
SUPABASE_URL = "https://qbqglutnudyymoblufqo.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFicWdsdXRudWR5eW1vYmx1ZnFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4MDQ3NzQsImV4cCI6MjA4MTM4MDc3NH0.wtuN2vk3lsqg2Bo0e_ypUKHOlXTc_ZxxzgIke2NUQyQ"
