[connections.supabase]
# El valor de la URL DEBE IR SIN COMILLAS y SIN CORCHETES
# NOTA: HE REEMPLAZADO LA CONTRASEÃ‘A REAL CON [...] POR SEGURIDAD.
url=postgresql://postgres:[DomiLeo1702]@db.emnqztaxybhbmkuryhem.supabase.co:5432/postgres

# Las bases de datos en Supabase se llaman "postgres"
database = "postgres" 

# El usuario por defecto en Supabase es "postgres"
username = "postgres"
