[connections.supabase]
# Reemplaza la URL completa con tu URI de Supabase
# Asegúrate de reemplazar "[YOUR-PASSWORD]" con la contraseña que elegiste.
url=postgresql://postgres:[Domi1702*]@db.emnqztaxybhbmkuryhem.supabase.co:5432/postgres

# Las bases de datos en Supabase se llaman "postgres"
database = "postgres" 

# El usuario por defecto en Supabase es "postgres"
username = "postgres"
